FORMAT: 1A
HOST: http://localhost:3000/

# Library REST

It is a API allowing to manage a virtual library.

## Books Collection [/books]

### List All Books [GET]

+ Response 200 (application/json)

        [
            {
                "readerId": null,
                "id": 1,
                "releaseDate": "2019-09-22",
                "title": "The title",
                "description": "The description"
            },
        ]

### Create a New Book [POST]

You may create your own question using this action. It takes a JSON
object containing a book.

+ Request (application/json)

        {
            "readerId": null,
            "id": 1,
            "releaseDate": "2019-09-22",
            "title": "The title",
            "description": "The description"
        },

+ Response 201 (application/json)